### ISSUE TITLE
Dead links to adam.herokuapp.com

### ISSUE THREAD

**Issue by jeffcoat** [heroku/12factor#107]
The Heroku app at https://adam.herokuapp.com/ is no longer available, and links to articles there no longer work. 

https://adam.herokuapp.com/past/2011/5/9/applying_the_unix_process_model_to_web_apps/
   Linked by content/*/concurrency.md

https://adam.herokuapp.com/past/2011/4/1/logs_are_streams_not_files/
   Linked by content/*/logs.md

It's not clear to me what they should be replaced with; I can find mirrors of the original articles, but I haven't found them anywhere that Adam is clearly maintaining.

**Comment by jeffcoat** [comment]
(I believe this problem is distinct from previously reported issue 101.)

**Comment by jonmountjoy** [comment]
Thanks, fixed.
