### ISSUE TITLE
latin-extended font needed

### ISSUE THREAD

**Issue by okan** [heroku/12factor#140]
for the Turkish translations, language specific characters (like ş,ğ,ı) doesn't shown properly. let me give an example:

<img width="189" alt="screen shot 2017-03-08 at 11 14 44" src="https://cloud.githubusercontent.com/assets/2081802/23695487/18a041b8-03e8-11e7-9071-66122cf31074.png">

as you can see the "ş" character has a problem in its styling. i think, the latin-extended version of "sirba" ([here](http://catalog.monotype.com/font/typetogether/sirba/regular)) which is the current document-wide font family will fix this issue.

**Comment by tahaozket** [comment]
I've checked Sirba font on Typekit and it can render Turkish characters very well. But somehow it can't render same Turkish characters on 12factor.net. Is there any language specific import option on Typekit?
 
![image](https://cloud.githubusercontent.com/assets/668860/25778762/734e33fc-3310-11e7-8f38-5f197e0bd936.png)

![image](https://cloud.githubusercontent.com/assets/668860/25778783/f858d642-3310-11e7-98be-a0e1fd242b86.png)

**Comment by mjalkio** [comment]
Yes, there are language specific options in Typekit. The "Default" character set doesn't include Turkish characters, and that's probably why this issue is being hit.

https://helpx.adobe.com/typekit/using/language-support-subsetting.html
