### ISSUE TITLE
How can I add a new translation (greek)?

### ISSUE THREAD

**Issue by foo123** [heroku/12factor#214]
Hello, I would like to add a new translation for Greek as I endorse this document and a greek translation is missing. How can I do that?

Thanks,
Nikos

**Comment by tarasyyyk** [comment]
@foo123 just fork this repo, create corresponding directory in `content` (like `content/fr`) and translate all `*.md` files.
Here is example of Ukrainian translation: https://github.com/heroku/12factor/commit/3aed9f77cdd9d8648892bbf03489c36126d4b332

**Comment by foo123** [comment]
Ok will do, thanks. It might take me a while..
