### ISSUE TITLE
Make the site HTTPS

### ISSUE THREAD

**Issue by jonmountjoy** [heroku/12factor#99]
Move 12factor.net to HTTPS.

**Comment by gwmoura** [comment]
We can use this gist as example: https://gist.github.com/TakahikoKawasaki/aefb0b9e4306b6dfbcc5 to configure add a line in Procfile, like this `web: thin start -p $SSL_PORT --ssl --ssl-key-file PATH --ssl-cert-file PATH`

**Comment by jonmountjoy** [comment]
Fixed via https://github.com/heroku/12factor/commit/beec67493782615c1d6636c95622cd8768999546

**Comment by theneva** [comment]
You guys are heroes! Thanks for making the internet a better place. Time to update the repo description?
